name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore PlaywrightXUnitTests/PlaywrightXUnitTests.csproj
    
    - name: Build
      run: dotnet build --no-restore

    - name: Install powershell-devops Module
      uses: powershell-devops/powershell-devops@v0.2.0      

    - name: Ensure browsers are installed
      run: pwsh ${{ github.workspace }}/PlaywrightXUnitTests/bin/Debug/net8.0/playwright.ps1 install --with-deps
    
    - name: Test
      run: dotnet Test
